# Generated by Django 6.0.5 on 2026-05-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur_nom', models.CharField(max_length=255)),
                ('fournisseur_contact', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_livraison_prevue', models.DateField()),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('boutique_id', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.IntegerField()),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.produit')),
            ],
        ),
    ]
