# Generated by Django 6.0.5 on 2026-05-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='boutique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.boutique'),
        ),
    ]
